plugins {
    alias(libs.plugins.blossom)
    id("java-library")
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

tasks.withType(JavaCompile).configureEach {
    options.release = 25
}

dependencies {
    implementation project(':api')

    api('net.kyori:adventure-api:5.2.0') {
        exclude(module: 'adventure-bom')
        exclude(module: 'checker-qual')
        exclude(module: 'annotations')
    }
    api('net.kyori:adventure-text-serializer-gson:5.2.0') {
        exclude(module: 'adventure-bom')
        exclude(module: 'adventure-api')
        exclude(module: 'gson')
    }
    api('net.kyori:adventure-text-serializer-legacy:5.2.0') {
        exclude(module: 'adventure-bom')
        exclude(module: 'adventure-api')
    }
    api('net.kyori:adventure-text-serializer-plain:5.2.0') {
        exclude(module: 'adventure-bom')
        exclude(module: 'adventure-api')
    }
    api('net.kyori:adventure-text-minimessage:5.2.0') {
        exclude(module: 'adventure-bom')
        exclude(module: 'adventure-api')
    }
    api('net.kyori:adventure-text-serializer-ansi:5.2.0') {
        exclude(module: 'adventure-bom')
        exclude(module: 'adventure-api')
        exclude(module: 'annotations')
    }
    api('net.kyori:ansi:1.1.1') {
        exclude(module: 'annotations')
    }
}

sourceSets {
    main {
        blossom {
            javaSources {
                property 'version', project.ext.fullVersion
            }
        }
    }
}
